### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by rafaelrinaldi** [eeue56/elm-for-web-developers#2]
Hey, thanks for putting up this list! It's really helpful.

I read the whole thing twice and something you said about Elm's performance has intrigued me:

> While Elm is fast at some things, **it's easy to write non-performant code in Elm if you stick too rigidly to the functional programming style**.

What does that mean? I thought this was exactly what made Elm performant in the first place.

**Comment by eeue56** [comment]
This is a good example - https://github.com/rluiten/stemmer/issues/1

**Comment by rafaelrinaldi** [comment]
@eeue56 Got it. Yeah, I think that's more of an issue of how Elm transpile to JavaScript as opposed to "following rigidly the functional programming style".
To have a good performance the rule of thumb should be to keep V8 optimizations in mind :+1: 

Thanks for clarifying.

**Comment by eeue56** [comment]
Yeah. Basically some approaches that you might typically prefer in Haskell aren't optimized in the same manner. So if you have performance issues, use JS benchmarking and performance tools to identify bits of your code which are slow, and most of the time it'll be down to things like nesting functions too deeply so that v8 can't precompile or inline
